spring.application.name=eureka
server.port=8761
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
logging.level.com.netflix.discovery=OFF
logging.level.com.netflix.eureka=OFF
eureka.instance.hostname=${EUREKA_HOSTNAME:localhost}
eureka.client.serviceUrl.defaultZone=http://${eureka.instance.hostname}:${server.port}/eureka/
eureka.instance.preferIpAddress=${EUREKA_PREFER_IP_ADDRESS:false}

management.endpoints.web.exposure.include=health,info,prometheus

management.tracing.sampling.probability=1.0
management.tracing.export.zipkin.endpoint=http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans

logstash.host=${LOGSTASH_HOST:localhost}
logstash.port=${LOGSTASH_PORT:5000}
