server.port=8090
spring.application.name=resource-processor
eureka.instance.lease-renewal-interval-in-seconds=${EUREKA_LEASE_RENEWAL_INTERVAL_SECONDS:5}
eureka.client.registry-fetch-interval-seconds=${EUREKA_REGISTRY_FETCH_INTERVAL_SECONDS:5}
eureka.instance.hostname=${EUREKA_HOSTNAME:localhost}
eureka.client.serviceUrl.defaultZone=http://${EUREKA_HOSTNAME:localhost}:8761/eureka/
eureka.instance.preferIpAddress=${EUREKA_PREFER_IP_ADDRESS:false}
eureka.instance.instanceId=${spring.application.name}:${spring.application.instance_id:${random.value}}
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}
rabbitmq.exchange=resource.exchange
rabbitmq.queue=resource.queue
rabbitmq.processed-queue=resource.processed.queue
rabbitmq.processed-routing-key=resource.processed
resource-service.api.url=${RESOURCE_SERVICE_URL:http://localhost:8071/resources}
song-service.api.url=${SONG_SERVICE_URL:http://localhost:8072/songs}

spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

spring.cloud.config.fail-fast=false
management.endpoints.web.exposure.include=health,info,refresh,prometheus

management.tracing.sampling.probability=1.0
management.tracing.export.zipkin.endpoint=http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans

spring.rabbitmq.template.observation-enabled=true
spring.rabbitmq.listener.simple.observation-enabled=true

logstash.host=${LOGSTASH_HOST:localhost}
logstash.port=${LOGSTASH_PORT:5000}
