server.port=8072
spring.jpa.hibernate.ddl-auto=update
spring.application.name=song-service
spring.datasource.url=jdbc:postgresql://localhost:5433/song-db
spring.datasource.username=postgres
spring.datasource.password=postgres

song-service.api.url=http://localhost:8072/songs