server.port=8072
spring.application.name=song-service
spring.datasource.url=${SONG_DB_URL:jdbc:postgresql://localhost:5433/song_db}
spring.datasource.username=${SONG_DB_USER:postgres}
spring.datasource.password=${SONG_DB_PASSWORD:postgres}
eureka.instance.lease-renewal-interval-in-seconds=${EUREKA_LEASE_RENEWAL_INTERVAL_SECONDS:5}
eureka.client.registry-fetch-interval-seconds=${EUREKA_REGISTRY_FETCH_INTERVAL_SECONDS:5}
eureka.instance.hostname=${EUREKA_HOSTNAME:localhost}
eureka.client.serviceUrl.defaultZone=http://${EUREKA_HOSTNAME:localhost}:8761/eureka/
eureka.instance.preferIpAddress=${EUREKA_PREFER_IP_ADDRESS:false}
eureka.instance.instanceId=${spring.application.name}:${spring.application.instance_id:${random.value}}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH_SERVER_ISSUER_URI:http://localhost:9000}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AUTH_SERVER_ISSUER_URI:http://localhost:9000}/oauth2/jwks

spring.config.import=optional:configserver:${CONFIG_SERVER_URL:http://localhost:8888}

spring.cloud.config.fail-fast=false
management.endpoints.web.exposure.include=health,info,refresh,prometheus

management.tracing.sampling.probability=1.0
management.tracing.export.zipkin.endpoint=http://${ZIPKIN_HOST:localhost}:9411/api/v2/spans

logstash.host=${LOGSTASH_HOST:localhost}
logstash.port=${LOGSTASH_PORT:5000}
