server.port=8072
spring.application.name=song-service
spring.datasource.url=${SONG_DB_URL:jdbc:postgresql://localhost:5433/song_db}
spring.datasource.username=${SONG_DB_USER:postgres}
spring.datasource.password=${SONG_DB_PASSWORD:postgres}