server.port=8071
spring.application.name=resource-service
spring.datasource.url=${RESOURCE_DB_URL:jdbc:postgresql://localhost:5432/resource_db}
spring.datasource.username=${RESOURCE_DB_USER:postgres}
spring.datasource.password=${RESOURCE_DB_PASSWORD:postgres}
song-service.api.url=${SONG_SERVICE_URL:http://localhost:8072/songs}
